### ISSUE TITLE
error while docker-compose up

### ISSUE THREAD

**Issue by haoziyeung** [PapenfussLab/PathOS#1]
hi,thanks for yours excellent job,i find a error when i'm installing pathOS,like below:

**[root@webserver docker]#** docker-compose up
Creating network "docker_default" with the default driver
Creating volume "docker_pathos-mariadb-data" with default driver
Pulling pathos-httpd (httpd:latest)...
latest: Pulling from library/httpd
10a267c67f42: Already exists
0782edf7745a: Pull complete
f3a72c4d9d02: Pull complete
dd6ec65d8a55: Pull complete
1b7920e1c0df: Pull complete
5b99e4053015: Pull complete
e720548ad189: Pull complete
Digest: sha256:72b55a7c15a4ee3d56ff19f83b57b82287714f91070b1f556a54e90da5eee3fa
Status: Downloaded newer image for httpd:latest
Pulling pathos-mariadb (mariadb:10)...
10: Pulling from library/mariadb
10a267c67f42: Already exists
c2dcc7bb2a88: Pull complete
17e7a0445698: Pull complete
9a61839a176f: Pull complete
64675690edb1: Pull complete
3de17e251488: Pull complete
f814b22b783e: Pull complete
733ce1f03439: Pull complete
fb7b719835fd: Pull complete
e13421f79ac0: Pull complete
8d3f82357729: Pull complete
a4f4cbdfcf7c: Pull complete
Digest: sha256:4b54358541679032f6c3a9d9fc944ad96d77ae72fecd6cb44bf18cf97743da24
Status: Downloaded newer image for mariadb:10
Pulling pathos-front (haproxy:alpine)...
alpine: Pulling from library/haproxy
cfc728c1c558: Pull complete
a369ce23edfb: Pull complete
70cebf7ec9cc: Pull complete
Digest: sha256:dd7cb9bed49f4af87b22b780275134da3616951c24c70d5d44f6112178abb1a5
Status: Downloaded newer image for haproxy:alpine
Creating docker_pathos-httpd_1 ...
Creating docker_pathos-mariadb_1 ...
Creating docker_pathos-httpd_1
Creating docker_pathos-mariadb_1 ... done
Creating docker_pathos-tools_1 ...
Creating docker_pathos-tomcat_1 ...
Creating docker_pathos-tools_1
Creating docker_pathos-tomcat_1 ... done
Creating docker_pathos-front_1 ...
Creating docker_pathos-front_1 ... error

ERROR: for docker_pathos-front_1  Cannot start service pathos-front: driver failed programming external connectivity on endpoint docker_pathos-front_1 (c7190af2ad7b5800f379ba84618ee147187698c49d96573f6c03c90c5399e438): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for pathos-front  Cannot start service pathos-front: driver failed programming external connectivity on endpoint docker_pathos-front_1 (c7190af2ad7b5800f379ba84618ee147187698c49d96573f6c03c90c5399e438): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

can you tell me why?
thank you

**Comment by kendoig** [comment]
Hi haoziyeung,
The line 'listen tcp 0.0.0.0:80: bind: address already in use' says that there is already another application running on port 80 on your computer. If you shut down whatever application is using  port 80, all should work.

Regards,
Ken Doig

**Comment by haoziyeung** [comment]
ooops,i see ,thank you again @kendoig ,maybe i'll have more questions in the future ,~~,thanks ,hope you have a nice day.

**Comment by kendoig** [comment]
No problem.
