### ISSUE TITLE
error with http docker port forwarding

### ISSUE THREAD

**Issue by haoziyeung** [PapenfussLab/PathOS#2]
sorry for disturb you again ,i have no error with docker compose up,but now some issue with this:
[root@webserver docker]# lsof -i:8081
COMMAND    PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
docker-pr 9883 root    4u  IPv6 76771450      0t0  TCP *:tproxy (LISTEN)
[root@webserver docker]# firewall-cmd --permanent --add-port=8081/tcp
success
[root@webserver docker]# firewall-cmd --reload
success
[root@webserver docker]# curl 127.0.0.1:8081
curl: (56) Recv failure: Connection reset by peer
[root@webserver docker]# firewall-cmd --permanent --add-port=443/tcp
success
[root@webserver docker]# firewall-cmd --reload
success
[root@webserver docker]# curl 127.0.0.1:8081
curl: (56) Recv failure: Connection reset by peer
[root@webserver docker]# curl 127.0.0.1:443
curl: (52) Empty reply from server

i open 8081,443 port in firewall-cmd,but i can't open localhost:8081 or localhost:443 with curl or chrome browser,can you tell me why?thank you,sorry about my bad english!
*ps,here is my browser snapshot:
![Uploading QQ截图20170515172426.png…]()

**Comment by haoziyeung** [comment]
i solved this problem,i install nginx before,and i have another website serve on my web server,now i want pathOS and my old web work together,i found error like before ,but i quit my nginx ,pathOS work finally,

**Comment by kendoig** [comment]
You shouldn't need to use firewall commands I don't think.
The browser accesses your localhost directly with the docker-front container using https://localhost/PathOS on port 443

Check that everything has come up on the right ports with this command:
    CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                      NAMES
    dc7333486170        docker_pathos-tools    "sleep infinity"         2 days ago          Up 55 seconds                                                  docker_pathos-tools_1
    b1a1dabe155b        haproxy:alpine         "/docker-entrypoin..."   2 days ago          Up 55 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docker_pathos-front_1
    f1495785b27a        docker_pathos-tomcat   "catalina.sh run"        2 days ago          Up 56 seconds       8080/tcp                                   docker_pathos-tomcat_1
    a30141fcad9c        mariadb:10             "docker-entrypoint..."   2 days ago          Up 57 seconds       3306/tcp                                   a30141fcad9c_a30141fcad9c_docker_pathos-mariadb_1
    2e04ed88cc4c        httpd                  "httpd-foreground"       2 days ago          Up 56 seconds       80/tcp                                     2e04ed88cc4c_2e04ed88cc4c_docker_pathos-httpd_1

Your english is way better than my Chinese ;-)

**Comment by haoziyeung** [comment]
[root@webserver docker]# docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
13e72d027529        haproxy:alpine         "/docker-entrypoin..."   11 seconds ago      Up 11 seconds       0.0.0.0:8081->8081/tcp   docker_pathos-front_1
6eebdb91e810        docker_pathos-tomcat   "catalina.sh run"        2 hours ago         Up 52 seconds       8080/tcp                 docker_pathos-tomcat_1
ea4de6c0e473        docker_pathos-tools    "sleep infinity"         2 hours ago         Up 51 seconds                                docker_pathos-tools_1
19ba125fe677        mariadb:10             "docker-entrypoint..."   2 hours ago         Up 53 seconds       3306/tcp                 docker_pathos-mariadb_1
4e3924226a93        httpd                  "httpd-foreground"       2 hours ago         Up 54 seconds       80/tcp                   docker_pathos-httpd_1

**Comment by haoziyeung** [comment]
but my nginx listen port 80,i change to 8081 in docker-compose.yml,why pathOS don't work,when nginx and httpd together?

**Comment by haoziyeung** [comment]
in fact ,i have my own previous web ,i don't want to shut my previous web, i want my web and pathOS work together...

**Comment by haoziyeung** [comment]
FINALLY,I SOLVED this problem all,my pathos-front/haproxy.cfg file is like below ,
frontend http
    bind :8082
    mode http
    acl curation    path_beg    /PathOS
    use_backend     pathos-tomcat   if curation
    default_backend pathos-httpd

frontend https
    bind :443 ssl crt /etc/ssl/private/cert.pem
    reqadd X-Forwarded-Proto:\ https
    mode http
    acl curation    path_beg    /PathOS
    use_backend     pathos-tomcat   if curation
    default_backend pathos-httpd

backend pathos-tomcat
    mode http
    balance roundrobin
    server pathos-tomcat    pathos-tomcat:8080

backend pathos-httpd
    mode http
    balance roundrobin
    server pathos-httpd pathos-httpd:80
and my "docker-compose.yml" is : 
    pathos-front:
        image: haproxy:alpine
        depends_on:
            - pathos-tomcat
            - pathos-httpd
        volumes:
            - ${PWD}/pathos-front/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
            - ${PATHOS_CERT}:/etc/ssl/private/cert.pem
        ports:
            - 8082:8082

you can close this issue,maybe other guys can solve this according my demo files.

**Comment by kendoig** [comment]
Fantastic, yes the port mapping happens in both places.
