### ISSUE TITLE
what is the initial USERNAME and PASSWD?

### ISSUE THREAD

**Issue by haoziyeung** [PapenfussLab/PathOS#3]
i have installed pathOS successfully,but i can't find the username and password in README?can you tell me what is the initial username and password?thank you ..

**Comment by haoziyeung** [comment]
by the way ,i can's login with **bioinformatics** and **pathos** in pathos-tools/pathos.properties.

**Comment by kendoig** [comment]
My fault, I updated the passwords this morning in https://github.com/PapenfussLab/PathOS/blob/master/Dockish-PathOS/docker_commands_readme.txt 
This should have been there earlier.
```javascript
#	The following role/user/pass combinations have been setup 
#	Role          User          Password
	ROLE_VIEWER   pathosviewer  pathos
	ROLE_LAB      pathoslab     pathos
	ROLE_CURATOR  pathoscurator pathos
	ROLE_ADMIN    pathosadmin   pathos
```

**Comment by haoziyeung** [comment]
okay,many thanks.i'll try.

**Comment by haoziyeung** [comment]
hi,i've log in succeffuly,thanks

**Comment by kendoig** [comment]
Well done !
